### ISSUE TITLE
GPU not allocated after `k3ai apply nvidia-gpu`

### ISSUE THREAD

**Issue by j-cunanan** [kf5i/k3ai-core#86] opened 2021-07-08 01:14 UTC
Hi! I would like to make use of my machines GPU (single RTX A6000) on Kubeflow pipelines.

Currently, CPU-only works fine but I need to use GPU resources for training.
After executing

`k3ai apply nvidia-gpu`

and verifying that

`kubectl get pods -A` gives

<pre>NAMESPACE            NAME                                                  READY   STATUS             RESTARTS   AGE
default              gpu-operator-test                                     0/1     Pending            0          15h
jupyter              jupyter-minimal-6565df8f74-n2hww                      1/1     Running            1          15h
kube-system          coredns-f9fd979d6-dg9m9                               1/1     Running            1          15h
kube-system          coredns-f9fd979d6-ml5zp                               1/1     Running            1          15h
kube-system          etcd-demo-win-kind-control-plane                      1/1     Running            0          46m
kube-system          kindnet-s252v                                         1/1     Running            2          15h
kube-system          kube-apiserver-demo-win-kind-control-plane            1/1     Running            0          46m
kube-system          kube-controller-manager-demo-win-kind-control-plane   1/1     Running            1          15h
kube-system          kube-proxy-j5mns                                      1/1     Running            1          15h
kube-system          kube-scheduler-demo-win-kind-control-plane            1/1     Running            1          15h
kube-system          nvidia-device-plugin-daemonset-qpdwb                  1/1     Running            1          15h
kubeflow             cache-deployer-deployment-84866455bb-462nf            1/1     Running            1          15h
kubeflow             cache-server-5c98c678f8-m5dqs                         1/1     Running            4          15h
kubeflow             first-pipeline-5fxxc-1217708725                       0/2     Completed          0          15h
kubeflow             first-pipeline-5fxxc-1430651520                       0/2     Completed          0          15h
kubeflow             first-pipeline-5fxxc-201314523                        0/2     Pending            0          15h
kubeflow             first-pipeline-5fxxc-3777309308                       0/2     Completed          0          15h
kubeflow             first-pipeline-5fxxc-731956426                        0/2     Completed          0          15h
kubeflow             metadata-envoy-deployment-6756c995c9-xwg8j            1/1     Running            1          15h
kubeflow             metadata-grpc-deployment-7cb87744c7-gsghl             0/1     CrashLoopBackOff   18         15h
kubeflow             metadata-writer-574df45956-54cb2                      0/1     CrashLoopBackOff   10         15h
kubeflow             minio-5b65df66c9-dthpd                                1/1     Running            1          15h
kubeflow             ml-pipeline-68644d4ddc-kqbfx                          0/1     CrashLoopBackOff   18         15h
kubeflow             ml-pipeline-persistenceagent-ffc9cfb96-2p4n9          1/1     Running            1          15h
kubeflow             ml-pipeline-scheduledworkflow-6d669f9bd7-p5hsp        1/1     Running            1          15h
kubeflow             ml-pipeline-ui-86bf65ccf7-44bxj                       1/1     Running            1          15h
kubeflow             ml-pipeline-viewer-crd-64dbbc8cc5-6xqjr               1/1     Running            2          15h
kubeflow             ml-pipeline-visualizationserver-78bcc958cd-l6pp6      1/1     Running            1          15h
kubeflow             mysql-f7b9b7dd4-hfxlp                                 1/1     Running            1          15h
kubeflow             workflow-controller-557d46b4bd-2zxc8                  1/1     Running            1          15h
local-path-storage   local-path-provisioner-78776bfc44-58hjt               1/1     Running            2          15h
</pre>

I thought GPU resources are now available to my cluster. But upon checking 

<pre><font color="#8AE234"><b>user@user-desktop</b></font>:<font color="#729FCF"><b>~</b></font>$ kubectl describe nodes 
Name:               demo-win-kind-control-plane
Roles:              master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=demo-win-kind-control-plane
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/master=
Annotations:        kubeadm.alpha.kubernetes.io/cri-socket: unix:///run/containerd/containerd.sock
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Wed, 07 Jul 2021 18:23:33 +0900
Taints:             &lt;none&gt;
Unschedulable:      false
Lease:
  HolderIdentity:  demo-win-kind-control-plane
  AcquireTime:     &lt;unset&gt;
  RenewTime:       Thu, 08 Jul 2021 10:05:49 +0900
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Thu, 08 Jul 2021 10:05:28 +0900   Wed, 07 Jul 2021 18:23:31 +0900   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Thu, 08 Jul 2021 10:05:28 +0900   Wed, 07 Jul 2021 18:23:31 +0900   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Thu, 08 Jul 2021 10:05:28 +0900   Wed, 07 Jul 2021 18:23:31 +0900   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Thu, 08 Jul 2021 10:05:28 +0900   Wed, 07 Jul 2021 18:23:57 +0900   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:  172.18.0.2
  Hostname:    demo-win-kind-control-plane
Capacity:
  cpu:                12
  ephemeral-storage:  959863856Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             32539168Ki
  pods:               110
Allocatable:
  cpu:                12
  ephemeral-storage:  959863856Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             32539168Ki
  pods:               110
System Info:
  Machine ID:                 94303fcf2f8d4ace8673d518890fb123
  System UUID:                b9b678e1-971c-41f1-a57c-be56e6fc028b
  Boot ID:                    8960095b-c1f1-4a43-83d6-621cc29dad3b
  Kernel Version:             5.4.0-77-generic
  OS Image:                   Ubuntu Groovy Gorilla (development branch)
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  containerd://1.4.0
  Kubelet Version:            v1.19.1
  Kube-Proxy Version:         v1.19.1
PodCIDR:                      10.244.0.0/24
PodCIDRs:                     10.244.0.0/24
ProviderID:                   kind://docker/demo-win-kind/demo-win-kind-control-plane
Non-terminated Pods:          (25 in total)
  Namespace                   Name                                                   CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                                                   ------------  ----------  ---------------  -------------  ---
  jupyter                     jupyter-minimal-6565df8f74-n2hww                       0 (0%)        0 (0%)      0 (0%)           0 (0%)         15h
  kube-system                 coredns-f9fd979d6-dg9m9                                100m (0%)     0 (0%)      70Mi (0%)        170Mi (0%)     15h
  kube-system                 coredns-f9fd979d6-ml5zp                                100m (0%)     0 (0%)      70Mi (0%)        170Mi (0%)     15h
  kube-system                 etcd-demo-win-kind-control-plane                       0 (0%)        0 (0%)      0 (0%)           0 (0%)         55m
  kube-system                 kindnet-s252v                                          100m (0%)     100m (0%)   50Mi (0%)        50Mi (0%)      15h
  kube-system                 kube-apiserver-demo-win-kind-control-plane             250m (2%)     0 (0%)      0 (0%)           0 (0%)         55m
  kube-system                 kube-controller-manager-demo-win-kind-control-plane    200m (1%)     0 (0%)      0 (0%)           0 (0%)         15h
  kube-system                 kube-proxy-j5mns                                       0 (0%)        0 (0%)      0 (0%)           0 (0%)         15h
  kube-system                 kube-scheduler-demo-win-kind-control-plane             100m (0%)     0 (0%)      0 (0%)           0 (0%)         15h
  kube-system                 nvidia-device-plugin-daemonset-qpdwb                   0 (0%)        0 (0%)      0 (0%)           0 (0%)         15h
  kubeflow                    cache-deployer-deployment-84866455bb-462nf             0 (0%)        0 (0%)      0 (0%)           0 (0%)         15h
  kubeflow                    cache-server-5c98c678f8-m5dqs                          0 (0%)        0 (0%)      0 (0%)           0 (0%)         15h
  kubeflow                    metadata-envoy-deployment-6756c995c9-xwg8j             0 (0%)        0 (0%)      0 (0%)           0 (0%)         15h
  kubeflow                    metadata-grpc-deployment-7cb87744c7-gsghl              0 (0%)        0 (0%)      0 (0%)           0 (0%)         15h
  kubeflow                    metadata-writer-574df45956-54cb2                       0 (0%)        0 (0%)      0 (0%)           0 (0%)         15h
  kubeflow                    minio-5b65df66c9-dthpd                                 20m (0%)      0 (0%)      100Mi (0%)       0 (0%)         15h
  kubeflow                    ml-pipeline-68644d4ddc-kqbfx                           250m (2%)     0 (0%)      500Mi (1%)       0 (0%)         15h
  kubeflow                    ml-pipeline-persistenceagent-ffc9cfb96-2p4n9           120m (1%)     0 (0%)      500Mi (1%)       0 (0%)         15h
  kubeflow                    ml-pipeline-scheduledworkflow-6d669f9bd7-p5hsp         0 (0%)        0 (0%)      0 (0%)           0 (0%)         15h
  kubeflow                    ml-pipeline-ui-86bf65ccf7-44bxj                        10m (0%)      0 (0%)      70Mi (0%)        0 (0%)         15h
  kubeflow                    ml-pipeline-viewer-crd-64dbbc8cc5-6xqjr                0 (0%)        0 (0%)      0 (0%)           0 (0%)         15h
  kubeflow                    ml-pipeline-visualizationserver-78bcc958cd-l6pp6       30m (0%)      0 (0%)      500Mi (1%)       0 (0%)         15h
  kubeflow                    mysql-f7b9b7dd4-hfxlp                                  100m (0%)     0 (0%)      800Mi (2%)       0 (0%)         15h
  kubeflow                    workflow-controller-557d46b4bd-2zxc8                   100m (0%)     0 (0%)      500Mi (1%)       0 (0%)         15h
  local-path-storage          local-path-provisioner-78776bfc44-58hjt                0 (0%)        0 (0%)      0 (0%)           0 (0%)         15h
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests     Limits
  --------           --------     ------
  cpu                1480m (12%)  100m (0%)
  memory             3160Mi (9%)  390Mi (1%)
  ephemeral-storage  0 (0%)       0 (0%)
  hugepages-1Gi      0 (0%)       0 (0%)
  hugepages-2Mi      0 (0%)       0 (0%)
Events:
  Type     Reason                   Age                From        Message
  ----     ------                   ----               ----        -------
  Normal   NodeHasSufficientMemory  15h (x5 over 15h)  kubelet     Node demo-win-kind-control-plane status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    15h (x4 over 15h)  kubelet     Node demo-win-kind-control-plane status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     15h (x4 over 15h)  kubelet     Node demo-win-kind-control-plane status is now: NodeHasSufficientPID
  Normal   Starting                 15h                kubelet     Starting kubelet.
  Normal   NodeHasSufficientMemory  15h                kubelet     Node demo-win-kind-control-plane status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    15h                kubelet     Node demo-win-kind-control-plane status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     15h                kubelet     Node demo-win-kind-control-plane status is now: NodeHasSufficientPID
  Normal   NodeAllocatableEnforced  15h                kubelet     Updated Node Allocatable limit across pods
  Normal   Starting                 15h                kube-proxy  Starting kube-proxy.
  Normal   NodeReady                15h                kubelet     Node demo-win-kind-control-plane status is now: NodeReady
  Normal   Starting                 55m                kubelet     Starting kubelet.
  Normal   NodeHasSufficientMemory  55m (x8 over 55m)  kubelet     Node demo-win-kind-control-plane status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    55m (x8 over 55m)  kubelet     Node demo-win-kind-control-plane status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     55m (x7 over 55m)  kubelet     Node demo-win-kind-control-plane status is now: NodeHasSufficientPID
  Normal   NodeAllocatableEnforced  55m                kubelet     Updated Node Allocatable limit across pods
  Warning  readOnlySysFS            55m                kube-proxy  CRI error: /sys is read-only: cannot modify conntrack limits, problems may arise later (If running Docker, see docker issue #24000)
  Normal   Starting                 55m                kube-proxy  Starting kube-proxy.
</pre>

GPU has not been allocated even though `nvidia-device-plugin-daemonset-qpdwb ` is running properly.

Thanks in advance for your help!

**Comment by alefesta** [comment] 2021-07-08 07:24
Hi, @j-cunanan, first of all, thanks for opening the issue, and really appreciated that you are using K3ai, I'm reviewing this right now, a couple of things:
1) I've updated the plugin to the latest version, could you give it try and see if anything changes?
2) What we do with the plugin is basically just pass the NVIDIA K8s YAML file so we assume the pre-requisites are satisfied.. if point 1 does not work could you try to follow their official documentation [here](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#install-nvidia-gpu-operator)? If it works I'll change the plugin to make use of the new GPU Operator

Thanks again for opening the issue!

**Comment by j-cunanan** [comment] 2021-07-09 01:14
Thank you for your quick resonse @alefesta !

1 did not work because I think I have'nt successfully done 2.

Doing the guide here: https://docs.nvidia.com/datacenter/cloud-native/kubernetes/install-k8s.html#option-2-installing-kubernetes-using-kubeadm

I successfully added my GPU without using the GPU operator but rather the multi-step method in the guide.

But when trying to add a GPU to a cluster made by `kind` or `k3ai` I couldn't make my GPU to work. 
I'll probably take more time debugging this.

Thanks again!

**Comment by alefesta** [comment] 2021-07-09 07:29
Humm...
So for `kind` the problem is that is a DnD (Docker in Docker) see the long thread [here](https://github.com/kubernetes-sigs/kind/pull/1886) they are still working on support GPU's. :(

For `k3ai` humm did you try to install k3s as a cluster (that is not a DnD) and then pass the GPU plugin? i.e.: `k3ai init --local k3s && k3ai apply nvidia-gpu` 

I would say that the easiest path is to move the plugin to use the GPU operator directly.. it shouldn't be too much of a problem since we were already targeting the support for helm and shell/PowerShell scripts as part of a plugin.
Let me work on this should be ready in a couple of weeks :)

**Comment by j-cunanan** [comment] 2021-07-14 00:37
ah i see. So after `k3ai init`
 
I modified the `.k3ai/config.yaml`  set `enable: true` on the localKind cluster instance.
Based from above, `k3ai apply nvidia-gpu` is expected to not work, right?

So now, enabled the localK3s and ran `k3ai init`
 but got

```
chmod: cannot access './home/user/k3s': No such file or directory
mv: cannot stat './home/user/k3s': No such file or directory

```
even though the file is there.

**Comment by alefesta** [comment] 2021-07-14 06:43
Ahhhhhhhhhhhhhhhhh `"+data.Spec.Linux+"; chmod +x .$HOME/k3s; sudo mv .$HOME/k3s /usr/local/bin;` my fault :) !!! Sorry about that.. in case if you look closely at the line above you'll notice a `.` in front of the $HOME ... that's why it cannot work. I'll fix that and I think is time to make a fix release of k3ai. Sorry about that really.

**Comment by alefesta** [comment] 2021-07-19 07:19
Ok I've fixed this will be in the next release of k3ai. Going to close this, thanks again for the issue @j-cunanan

**Closed by alefesta** 2021-07-19 07:19 UTC
Labels: area/bug, area/plugins
